package main

import (
	"flag"
	"fmt"
	"html/template"
	"os"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const XormEnumFieldTemplate = `
// Base xorm.io/xorm/convert

// FromDB implements convert.Conversion
func (x *{{ .GoIdent.GoName }}) FromDB(b []byte) error {
	key := string(b)
	value, ok := {{ .GoIdent.GoName }}_value[key]
	if ok {
		*x = {{ .GoIdent.GoName }}(value)
	}
	return nil
}

// ToDB implements convert.Conversion
func (x *{{ .GoIdent.GoName }}) ToDB() ([]byte, error) {
	return []byte(x.String()), nil
}
`

var XormEnumFieldTemplateParser = template.Must(template.New("message").Parse(XormEnumFieldTemplate))

func main() {
	flag.Parse()

	protogen.Options{
		ParamFunc: flag.CommandLine.Set,
	}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}
			if len(f.Messages) == 0 {
				continue
			}
			if len(f.Enums) == 0 && !hasEnums(f.Messages) {
				continue
			}
			filename := f.GeneratedFilenamePrefix + "_xorm.pb.go"
			file := plugin.NewGeneratedFile(filename, f.GoImportPath)
			applyTemplate(file, f)
		}
		return nil
	})
}

func hasEnums(ms []*protogen.Message) bool {
	for _, m := range ms {
		if len(m.Enums) > 0 {
			return true
		}
		if hasEnums(m.Messages) {
			return true
		}
	}
	return false
}

func applyTemplate(file *protogen.GeneratedFile, f *protogen.File) {
	file.P(`// Code generated by protoc-gen-go-xorm, DO NOT EDIT!`)
	file.P(`// Power by nfangxu<niu.fangxu08348@cetccst.com>`)
	file.P(``)
	file.P(`package ` + f.GoPackageName)
	applyEnums(file, f.Enums)
	applyMessages(file, f.Messages)
}

func applyMessages(file *protogen.GeneratedFile, ms []*protogen.Message) {
	for _, m := range ms {
		applyEnums(file, m.Enums)
		applyMessages(file, m.Messages)
	}
}

func applyEnums(file *protogen.GeneratedFile, enums []*protogen.Enum) {
	for _, enum := range enums {
		if err := genEnum(file, enum); err != nil {
			fmt.Fprintf(os.Stderr, "protoc-gen-go-xorm error: %+v\n", err)
		}
	}
}

func genEnum(file *protogen.GeneratedFile, enum *protogen.Enum) error {
	return XormEnumFieldTemplateParser.Execute(file, enum)
}
